---
title: "comandos homework8"
author: "Andreza Palma"
date: "21/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Script de ajuda para homework 8
###Lembre-se de instalar e carregar os pacotes necessários. 

##Exercício 1:

## Importação dos dados do PIB
``` {r}
#Sem ajuste sazonal
tabela = get_sidra(api='/t/1620/n1/all/v/all/p/all/c11255/90687,90691,90696,90707,93404,93405,93406,93407,93408/d/v583%202')

#com ajuste sazonal
tabela_sa = get_sidra(api='/t/1621/n1/all/v/all/p/all/c11255/90687,90691,90696,90707,93404,93405,93406,93407,93408/d/v584%202')

series = c(90687,90691,90696,90707,93404,93405,93406,93407,93408)
names = c('Agro', 'Ind', 'Serv', 'PIB',
          'Consumo', 'Governo', 'FBCF',
          'Exportação', 'Importação')
```

#Para arrumar os dados
#Forma 1:
```{r}
pib = matrix(NA, ncol=length(series), 
             nrow=nrow(tabela)/length(series))
for(i in 1:length(series)){
  pib[,i] = tabela$Valor[tabela$
                           `Setores e subsetores (Código)`
                         ==series[i]] 
  pib = ts(pib, start=c(1996,01), freq=4)
  colnames(pib) = names
}

tail(pib)
```

#Forma2 (para dados sem ajuste sazonal)
```{r}
tabela = get_sidra(api='/t/1620/n1/all/v/all/p/all/c11255/90687,90691,90696,90707,93404,93405,93406,93407,93408/d/v583%202') %>%
  mutate(date = as.yearqtr(`Trimestre (Código)`, format='%Y%q')) %>%
  select(date, `Setores e subsetores`, Valor) %>%
  spread(`Setores e subsetores`, Valor) %>%
  rename(`Consumo do Governo` = `Despesa de consumo da administração pública`) %>%
  as_tibble()
```

####Exercício 3:
```{r}

data = get_annual_market_expectations(c('PIB Total', 'IPCA',
                                        'Taxa de câmbio',
                                        'Meta para taxa over-selic'),
                                      start_date = '2012-01-01')

```

